import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link';
import ImgCard from '../comps/ImgCard';
import NavBar from '../comps/v2';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/boiler">GO TO BOILER</Link>
      <ImgCard bg="#DAD ">This is a children in the tag </ImgCard>
      <ImgCard tcl="#ABC980" img="http://placekitten.com/400/400"></ImgCard>
    </div>
  )
}
